#!/usr/bin/env python3
"""Append monitoring signals and maintain simple task hypotheses."""

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

VALID_CADENCES = {"daily", "weekly"}
VALID_CONFIDENCE = {"high", "medium", "low"}
VALID_DIRECTIONS = {"support", "contradict", "archive"}
VALID_STATUSES = {"new", "watching", "confirmed", "reversed", "archived"}
DEFAULT_THRESHOLD = 3


def slugify(value):
    normalized = re.sub(r"[^a-z0-9]+", "-", value.strip().lower())
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    if not normalized:
        raise ValueError("signal key must contain at least one letter or digit")
    return normalized


def read_threshold(workspace, task_id):
    task_path = workspace / "tasks" / f"{task_id}.yaml"
    if not task_path.exists():
        return DEFAULT_THRESHOLD
    text = task_path.read_text()
    match = re.search(r"signal_confirmation_threshold:\s*(\d+)", text)
    if not match:
        return DEFAULT_THRESHOLD
    return max(1, int(match.group(1)))


def load_hypotheses(path, task_id, threshold):
    if not path.exists() or not path.read_text().strip():
        return {
            "task_id": task_id,
            "updated_at": "",
            "review_cadence": "weekly",
            "signal_confirmation_threshold": threshold,
            "hypotheses": [],
        }
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"{path} must use the JSON-compatible YAML format generated by this skill: {exc}"
        ) from exc
    data.setdefault("task_id", task_id)
    data.setdefault("review_cadence", "weekly")
    data.setdefault("signal_confirmation_threshold", threshold)
    data.setdefault("hypotheses", [])
    return data


def save_hypotheses(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")


def find_hypothesis(data, hypothesis_id):
    for item in data["hypotheses"]:
        if item.get("id") == hypothesis_id:
            return item
    return None


def next_status(item, direction, threshold):
    if direction == "archive":
        return "archived"
    if direction == "contradict":
        return "reversed"
    evidence_count = int(item.get("evidence_count", 0))
    if evidence_count <= 1:
        return "new"
    if evidence_count >= threshold:
        return "confirmed"
    return "watching"


def append_ledger(path, record):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as fh:
        fh.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")


def append_rolling_memory(path, record):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text("# Rolling Memory\n\n## Event Log\n\n")
    line = (
        f"- {record['date']} [{record['status']}] {record['signal_key']}: "
        f"{record['summary']} Confidence: {record['confidence']}. Evidence: {record['evidence']}\n"
    )
    with path.open("a") as fh:
        fh.write(line)


def update_memory(args):
    workspace = Path(args.workspace).resolve()
    task_id = slugify(args.task_id)
    signal_key = slugify(args.signal_key)
    memory_dir = workspace / "memory" / task_id
    threshold = args.threshold or read_threshold(workspace, task_id)
    run_date = args.date or date.today().isoformat()

    ledger_path = memory_dir / "signal-ledger.jsonl"
    hypotheses_path = memory_dir / "hypotheses.yaml"
    rolling_path = memory_dir / "rolling-memory.md"

    data = load_hypotheses(hypotheses_path, task_id, threshold)
    item = find_hypothesis(data, signal_key)
    if item is None:
        item = {
            "id": signal_key,
            "statement": args.statement or args.summary,
            "status": "new",
            "evidence_count": 0,
            "contradiction_count": 0,
            "confidence": args.confidence,
            "last_reviewed": "",
            "next_review": data.get("review_cadence", "weekly"),
            "evidence": [],
        }
        data["hypotheses"].append(item)

    if args.direction == "support":
        item["evidence_count"] = int(item.get("evidence_count", 0)) + 1
    elif args.direction == "contradict":
        item["contradiction_count"] = int(item.get("contradiction_count", 0)) + 1

    item["status"] = next_status(item, args.direction, threshold)
    item["confidence"] = args.confidence
    item["last_reviewed"] = run_date
    item.setdefault("evidence", []).append(
        {
            "date": run_date,
            "direction": args.direction,
            "summary": args.summary,
            "evidence": args.evidence,
        }
    )

    data["updated_at"] = run_date
    data["signal_confirmation_threshold"] = threshold

    record = {
        "date": run_date,
        "cadence": args.cadence,
        "signal_key": signal_key,
        "dimension": args.dimension,
        "status": item["status"],
        "summary": args.summary,
        "evidence": args.evidence,
        "confidence": args.confidence,
        "direction": args.direction,
        "evidence_count": item["evidence_count"],
        "contradiction_count": item["contradiction_count"],
    }

    append_ledger(ledger_path, record)
    save_hypotheses(hypotheses_path, data)
    append_rolling_memory(rolling_path, record)

    print(json.dumps(record, ensure_ascii=False, sort_keys=True))


def parse_args():
    parser = argparse.ArgumentParser(description="Append a monitoring signal to task memory.")
    parser.add_argument("--workspace", required=True)
    parser.add_argument("--task-id", required=True)
    parser.add_argument("--date")
    parser.add_argument("--cadence", default="daily", choices=sorted(VALID_CADENCES))
    parser.add_argument("--signal-key", required=True)
    parser.add_argument("--dimension", required=True)
    parser.add_argument("--summary", required=True)
    parser.add_argument("--evidence", required=True)
    parser.add_argument("--statement")
    parser.add_argument("--confidence", default="medium", choices=sorted(VALID_CONFIDENCE))
    parser.add_argument("--direction", default="support", choices=sorted(VALID_DIRECTIONS))
    parser.add_argument("--threshold", type=int)
    return parser.parse_args()


if __name__ == "__main__":
    try:
        update_memory(parse_args())
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        sys.exit(1)
